### ISSUE TITLE
Resume Content feature now missing (H5P.com / Canvas integration)

### ISSUE THREAD

**Issue by HeyTC-au** [otacke/h5p-structure-strip#35]
When: 1 Jul 2022.  First noticed 14 June. 

Check box to allow Resume content is missing.

Structure Strip > LTI Settings > [_] Resume Content

The feature was working start of 19 May but as of 14 June no longer.  The IT Admin has not changed any settings.  The Resume content is working on other H5P tools within the same instance (Documentation, Essay, Drag & Drop).

This is part of the H5p.com / Canvas integration.

**Comment by HeyTC-au** [comment]
@otacke  - thanks for clarifying.  Will close this issue.

**Comment by otacke** [comment]
Hi! What do you mean by "not planned"? Structure Strip supported the "save content state" feature that H5P offers (referencing the software here, not the platform integration H5P.com) from day one on.
